### ISSUE TITLE
Enhance Data Access view Configuration to show order of categories

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1682]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Data Access View (DAV) options under configuration shows a list of available categories to show on screen. The order here does not get translated to the order shown in the actual Data Access View. 

That is, if I change the order of the DAV categories in the configuration, I still have the default order shown in the data access view and my changes are not reflected. As an enhancement it would be great to expand the functionality to control the order of the Categories on display. 

### Steps to Reproduce

1.  Go Set up > Options > Data Access View
2. Change the order around to be different to the default. This can be done by hiding all categories and selecting the category to be visible in the desired order
3. Save and exit Constellation for the changes to apply
4. Restart constellation and check the order of Categories > this is the default order and not the order I have entered in the DAV set up options

**Expected behaviour:** as an enhancement the order of categories in DAV config is shown in the DAV and there is an option to change the ordering within the visible categories

**Actual behaviour:** 
![image](https://user-images.githubusercontent.com/83679004/163908281-83609496-0857-49ea-86d4-51dd8cba2504.png)

**Reproduces how often:** 100%

### Additional Information

It would be great to build on the awesome work that was done to be able to hide the categories.

**Comment by GammaVel** [comment]
Hi @altair1673, thanks very much for working on this. It looks like there could be an issue here if you have hidden a category in version 2.10 and then open up the latest nightly build. 

In version 2.10 I had hidden one of the columns from the DAV. When I loaded the latest windows nightly build (v2.11) it didn't shown any of my categories, it was blank. Here is what it looked like:

![image](https://github.com/constellation-app/constellation/assets/83679004/749b48c2-0713-4fb9-9301-8db36ce7cda8)

I tried to replicate this bug by repeating the exact same steps and the next time Enrichment was shown both as a visible and a hidden column

![image](https://github.com/constellation-app/constellation/assets/83679004/a01561c5-fff0-4f7d-a4ba-dff7f8bffce2)

Just wondering if you could please take a look and see if you get the same behaviour?  
Thanks.

**Comment by antares1470** [comment]
@GammaVel I've just fixed some things with the category ordering and perhaps some of issues you identified there may have been fixed. Are you able to give it another test?

**Comment by GammaVel** [comment]
HI @antares1470, thanks for letting me know about the updates. I repeated the same steps that were in the original bug and I still have an issue. In v2.10 I hid the Enrichment category. I opened v2.11 from the latest nightly build and it appears as hidden and in the visible list. It does not actually show up as a category. 
Here is a screenshot of it:
![image](https://github.com/constellation-app/constellation/assets/83679004/d16a0007-af46-411d-968d-45b8ffbcf1b1)

**Comment by HolandCrick** [comment]
This one looks good, it's working now.

**Comment by HolandCrick** [comment]
Re-tested the scenario, where there was hidden category in v2.10 this was displayed both in available column and hidden column. In v2.11 latest nightly build issue was still happening; however, it was able to restore to default settings. Which is a good workaround.
